image: debian/stable
packages:
  - build-essential
  - clang-format-13
tasks:
  - check-format: |
      cd opendeco
      clang-format-13 -n --Werror src/*.c src/*.h test/*.c
  - build: |
      cd opendeco
      make
  - test: |
      cd opendeco
      make test
artifacts:
  - opendeco/opendeco
