image: debian/stable
packages:
  - build-essential
  - clang-format-13
sources:
  - https://git.sr.ht/~tsegers/opendeco
tasks:
  - check-format: |
      cd opendeco
      clang-format-13 -n --Werror src/*.c src/*.h test/*.c test/*.h
  - build: |
      cd opendeco
      make
  - test: |
      cd opendeco
      make test
artifacts:
  - opendeco/opendeco
